### ISSUE TITLE
Wrong requirement in HasCutAbility function

### ISSUE THREAD

**Issue by YooTenz** [ScrPits/PROShine#23]
The HasCutAbility() function in GameClient has wrong requirements for Sinnoh. You can use Cut right after receiving the first badge which is the "Coal Badge", not the "Forest Badge".

**Comment by PreciousTrainer** [comment]
OKay thanks for ur comment I'll now commit and the owner will accept it :D

**Comment by ScrPits** [comment]
please note. this function was pulled thru official sources. please push this to the official as well.

**Comment by ScrPits** [comment]
Issue has been solved by Precious.
thanks for the report
